default:
  DEBUG: true
  NAME: backend
  HOST: 0.0.0.0
  PORT: 8080
  WORKERS: 4
  FAST_API_PATH: backend.app:app
  RELOADED: false
  LOG_LEVEL: info


  DATABASE:
    DRIVER: postgresql+asyncpg
    HOST: db
    PORT: 5432
    USER: postgres
    PASSWORD: postgres
    NAME: backend

  REDIS:
    HOST: redis
    PORT: 6379
    DB: 0
    PASSWORD: redis

  SMTP:
    SERVER: smtp.yandex.ru
    PORT: 465
    USERNAME: ''
    PASSWORD: ''

  OTP:
    EXPIRATION: 300
    MAX_ATTEMPTS: 5
    MAX_SENDS: 5
    COOLDOWN_TIME: 60
    BLOCK_TIME: 600

  LOGGING:
    version: 1
    disable_existing_loggers: False
    formatters:
      default:
        format: "%(levelname)-8s#  [%(asctime)s.%(msecs)d]  %(filename)s [LINE:%(lineno)d]:  %(message)s"
    handlers:
      console:
        level: INFO
        class: logging.StreamHandler
        formatter: default
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers: [ console ]