default:
  DEBUG: true
  NAME: backend
  HOST: 0.0.0.0
  PORT: 8080
  WORKERS: 4
  FAST_API_PATH: backend.app:app
  RELOADED: false
  LOG_LEVEL: info


  DATABASE:
    DRIVER: postgresql
    HOST: localhost
    PORT: 5732
    USER: postgres
    PASSWORD: postgres
    NAME: qme_back

  LOGGING:
    version: 1
    disable_existing_loggers: False
    formatters:
      default:
        format: "%(levelname)-8s#  [%(asctime)s.%(msecs)d]  %(filename)s [LINE:%(lineno)d]:  %(message)s"
    handlers:
      console:
        level: INFO
        class: logging.StreamHandler
        formatter: default
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers: [ console ]