services:
  backend:
    build:
      context: .
    container_name: main-app
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db

  db:
    container_name: main_db
    image: pgvector/pgvector:0.8.0-pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    ports:
      - "5431:5432"
    networks:
      - backend

  redis:
    container_name: main_redis
    image: redis:latest
    command: ["redis-server", "--requirepass", "redis"]
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
