services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "redis"]
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
