"""Remove different group fields

Revision ID: 2e93cdb698dd
Revises: 18a6c4d7a7cf
Create Date: 2025-01-26 18:40:51.645805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e93cdb698dd'
down_revision: Union[str, None] = '18a6c4d7a7cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('to_group_id', sa.Integer(), nullable=False))
    op.drop_constraint('transfer_to_lab_group_id_fkey', 'transfer', type_='foreignkey')
    op.drop_constraint('transfer_to_lecture_group_id_fkey', 'transfer', type_='foreignkey')
    op.drop_constraint('transfer_to_consultation_group_id_fkey', 'transfer', type_='foreignkey')
    op.drop_constraint('transfer_to_practice_group_id_fkey', 'transfer', type_='foreignkey')
    op.create_foreign_key(None, 'transfer', 'group', ['to_group_id'], ['id'])
    op.drop_column('transfer', 'to_consultation_group_id')
    op.drop_column('transfer', 'to_practice_group_id')
    op.drop_column('transfer', 'to_lab_group_id')
    op.drop_column('transfer', 'to_lecture_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('to_lecture_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transfer', sa.Column('to_lab_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transfer', sa.Column('to_practice_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transfer', sa.Column('to_consultation_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transfer', type_='foreignkey')
    op.create_foreign_key('transfer_to_practice_group_id_fkey', 'transfer', 'group', ['to_practice_group_id'], ['id'])
    op.create_foreign_key('transfer_to_consultation_group_id_fkey', 'transfer', 'group', ['to_consultation_group_id'], ['id'])
    op.create_foreign_key('transfer_to_lecture_group_id_fkey', 'transfer', 'group', ['to_lecture_group_id'], ['id'])
    op.create_foreign_key('transfer_to_lab_group_id_fkey', 'transfer', 'group', ['to_lab_group_id'], ['id'])
    op.drop_column('transfer', 'to_group_id')
    # ### end Alembic commands ###
