"""added fileds to elective

Revision ID: 78b5866c4716
Revises: 239721cc423d
Create Date: 2025-01-23 15:18:19.344130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b5866c4716'
down_revision: Union[str, None] = '239721cc423d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elective', sa.Column('modeus_link', sa.String(), nullable=True))
    op.add_column('elective', sa.Column('description', sa.String(), nullable=True))
    op.add_column('elective', sa.Column('text', sa.Integer(), nullable=True))
    op.add_column('elective', sa.Column('questions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elective', 'questions')
    op.drop_column('elective', 'text')
    op.drop_column('elective', 'description')
    op.drop_column('elective', 'modeus_link')
    # ### end Alembic commands ###
