"""made ManyToMany transfer-grop relationship

Revision ID: 88111a353065
Revises: 2e93cdb698dd
Create Date: 2025-01-26 23:27:41.090448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88111a353065'
down_revision: Union[str, None] = '2e93cdb698dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('transfer', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transfer', 'from_elective_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transfer', 'to_elective_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('transfer_to_group_id_fkey', 'transfer', type_='foreignkey')
    op.drop_column('transfer', 'to_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('to_group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('transfer_to_group_id_fkey', 'transfer', 'group', ['to_group_id'], ['id'])
    op.alter_column('transfer', 'to_elective_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transfer', 'from_elective_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transfer', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('transfer_group')
    # ### end Alembic commands ###
